# Docker v2
# Build or push Docker images, login or logout, start or stop containers, or run a Docker command.

pool:
  name: DevSecOps
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kfeelixge/alpine'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: aquasecScanner@4
  inputs:
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    connection: 'Aqua SaaS'
    caCertificates: true
    scanner: 'registry.aquasec.com/scanner:2301.4.11'
    runOptions: '-e AQUA_TOKEN=f2649adb8a56541615910187646475f2f65749ee'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kfeelixge/alpine'
    command: 'push'
