# Docker v2
# Build or push Docker images, login or logout, start or stop containers, or run a Docker command.

pool:
  name: DevSecOps
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kfeelixge/alpine'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: aquasecScanner@4
  inputs:
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    connection: 'Aqua SaaS'
    caCertificates: true
    image: 'kfeelixge/alpine:$(Build.BuildId)'
    scanner: 'registry.aquasec.com/scanner:2303.7.5'
    runOptions: '-e AQUA_TOKEN=18887b24-1999-47d6-b599-317902432f65'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kfeelixge/alpine'
    command: 'push'


