# Docker v2
# Build or push Docker images, login or logout, start or stop containers, or run a Docker command.
- task: aquasecScanner@4
  inputs:
    image: 'alpine:latest'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    connection: 'Aqua SaaS'
    caCertificates: true