# Docker v2
# Build or push Docker images, login or logout, start or stop containers, or run a Docker command.

pool:
  name: DevSecOps
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'kfeelixge/alpine'
    command: 'build'
    Dockerfile: '**/Dockerfile'
